spring:
  application:
    name: jobkrchatbot
  profiles:
    active: local
  
  # 환경변수 파일 로드
  config:
    import: optional:file:${user.dir}/env.properties
  
  # PostgreSQL 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/chatbot
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# OpenAI API 설정
openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-api-key-here}
    url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
    model: ${OPENAI_MODEL:gpt-4}

# Anthropic Claude API 설정
anthropic:
  api:
    key: ${ANTHROPIC_API_KEY:your-anthropic-api-key-here}
    url: ${ANTHROPIC_API_URL:https://api.anthropic.com/v1/messages}
    model: ${ANTHROPIC_MODEL:claude-3-sonnet-20240229}

# LLM 제공자 선택 (openai 또는 anthropic)
llm:
  provider: ${LLM_PROVIDER:openai}