# 로컬 개발 환경 설정
server:
  port: 8080

logging:
  level:
    backend.jobkrchatbot: DEBUG
    org.springframework.web: DEBUG

# OpenAI API 설정 (로컬)
openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-api-key-here}
    url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
    model: ${OPENAI_MODEL:gpt-4}