spring:
  application:
    name: jobkrchatbot
  profiles:
    active: local

# OpenAI API 설정
openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-api-key-here}
    url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
    model: ${OPENAI_MODEL:gpt-4}