# 로컬 환경 설정
spring:
  application:
    name: jobkrchatbot

# OpenAI API 설정 (로컬 환경)
openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-api-key-here}
    url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
    model: ${OPENAI_MODEL:gpt-4}