server:
  port: 8082

spring:
  application:
    name: llm-service
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: llm-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

openai:
  api:
    key: ${OPENAI_API_KEY:your-api-key-here}
    url: https://api.openai.com/v1/chat/completions
    model: gpt-4o

claude:
  api:
    key: ${CLAUDE_API_KEY:your-claude-api-key-here}
    url: https://api.anthropic.com/v1/messages
    model: claude-3-sonnet-20240229
    version: 2023-06-01

logging:
  level:
    backend.jobkrchatbot: DEBUG
    org.springframework.kafka: DEBUG 