server:
  port: 8082

spring:
  application:
    name: llm-service
  
  jpa:
    enabled: false
  
  kafka:
    bootstrap-servers: kafka1:29092,kafka2:29093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Exactly-Once 보장 설정
      enable-idempotence: true
      acks: all
      retries: 3
      max-in-flight-requests-per-connection: 1
    consumer:
      group-id: llm-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Exactly-Once 보장 설정
      isolation-level: read_committed
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions
    model: gpt-4o

claude:
  api:
    key: ${CLAUDE_API_KEY}
    url: https://api.anthropic.com/v1/messages
    model: claude-sonnet-4-20250514
    version: 2023-06-01

logging:
  level:
    backend.jobkrchatbot.llmservice: DEBUG
    org.springframework.kafka: DEBUG
