server:
  port: 8082

spring:
  application:
    name: llm-service
  
  jpa:
    enabled: false
  
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer:
      group-id: llm-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions
    model: gpt-4o

logging:
  level:
    backend.jobkrchatbot.llmservice: DEBUG
    org.springframework.kafka: DEBUG
